services:
  - type: web
    name: taskflow-backend
    env: python
    rootDir: .
    buildCommand: |
      python --version && pwd && ls -la && pip install --upgrade pip && pip install --use-deprecated=legacy-resolver -r backend/requirements.txt
    startCommand: |
      cd backend && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: DATABASE_URL
        fromDatabase:
          name: taskflow-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://taskflow-ai.onrender.com,http://localhost:3000,https://taskflow-frontend.onrender.com
      - key: LOG_LEVEL
        value: INFO
      - key: API_PREFIX
        value: /api/v1
      - key: DEBUG
        value: false
      - key: TESTING
        value: false
      - key: PORT
        value: 8000
      - key: WORKERS
        value: 4
      - key: TIMEOUT
        value: 120
      - key: RELOAD
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: ALLOWED_HOSTS
        value: taskflow-ai.onrender.com,localhost
      - key: SSL_REDIRECT
        value: true
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: CSRF_COOKIE_SECURE
        value: true
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: SECURE_HSTS_SECONDS
        value: 31536000
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: true
      - key: SECURE_HSTS_PRELOAD
        value: true
      - key: SECURE_PROXY_SSL_HEADER
        value: X-Forwarded-Proto,https

databases:
  - name: taskflow-db
    databaseName: taskflow
    user: taskflow
    plan: free 