services:
  - type: web
    name: taskflow-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd backend
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir --no-build-isolation -r requirements.txt
      alembic upgrade head
    startCommand: cd backend && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        fromDatabase:
          name: taskflow-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: FRONTEND_URL
        value: https://taskflow-ai.vercel.app
      - key: WORKERS
        value: "4"
      - key: TIMEOUT
        value: "120"
      - key: PYTHONPATH
        value: /app
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: PIP_CONSTRAINT
        value: "pydantic-core>=2.20.0"

databases:
  - name: taskflow-db
    plan: free 