services:
  - type: web
    name: taskflow-backend
    env: docker
    region: oregon
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskflow-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: FRONTEND_URL
        value: https://taskflow-frontend.onrender.com
      - key: WORKERS
        value: 4
      - key: TIMEOUT
        value: 120

databases:
  - name: taskflow-db
    databaseName: taskflow
    plan: free 