services:
  - type: web
    name: taskflow-backend
    runtime: python
    region: oregon
    plan: free
    rootDir: backend
    pythonVersion: "3.11"
    
    buildCommand: |
      pip install --upgrade pip
      pip install --use-deprecated=legacy-resolver -r requirements.txt
    
    startCommand: |
      alembic upgrade head && 
      gunicorn app.main:app \
        --workers 4 \
        --worker-class uvicorn.workers.UvicornWorker \
        --bind 0.0.0.0:$PORT \
        --timeout 120 \
        --access-logfile - \
        --error-logfile - \
        --chdir /opt/render/project/src/backend
    
    healthCheckPath: /health
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskflow-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: FRONTEND_URL
        value: https://taskflow-frontend.onrender.com
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: PYTHONUNBUFFERED
        value: "1"

databases:
  - name: taskflow-db
    databaseName: taskflow
    user: taskflow_user
    region: oregon
    plan: free
    version: "15" 