services:
  - type: web
    name: taskflow-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://taskflow-frontend-gsox0fqlm-gilad-s-projects.vercel.app
      - key: VITE_API_URL
        value: https://taskflow-backend-ov87.onrender.com 